image:
  - Visual Studio 2015

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

matrix:
  fast_finish: true

shallow_clone: true

skip_commits:
  files:
    - .github/
    - .editorconfig
    - .gitignore
    - LICENSE
    - README.md

build:
  project: samples\Samples.sln
  verbosity: minimal

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))